models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./cs4501:/app
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory ./cs4501/app --reload-on-changes ./cs4501/app/foo/foo/wsgi.py"